version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    steps:
      - run:
          name: run tests and generate coverage
          command: npm cov
      - codecov/upload:
          file: {{ /coverage }}